production:
  adapter: postgresql
  database: tv_production
  username: rails
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>

development:
  adapter: postgresql
  database: tv_development
  pool: 5
  timeout: 5000
  username: rails
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>

test:
  adapter: postgresql
  database: tv_test
  pool: 5
  timeout: 5000
  username: rails
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>
