production:
  adapter: postgresql
  database: tv_production
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: tv
  password: <%= ENV['TV_DATABASE_PASSWORD'] %>

development:
  adapter: postgresql
  database: tv_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: tv_test
  pool: 5
  timeout: 5000
